version: '3.1'

services:
  web:
    network_mode: default
    image: nginx:alpine

    restart: always
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    volumes: 
      - ./html:/usr/share/nginx/html
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 20080:80
